[build]
  command = "true"
  publish = "./html"

[functions]
  directory = "./functions"
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda"]

[[redirects]]
  from = "/screenshots/*"
  to = "/.netlify/functions/screenshots/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
