[build]
  command = "true"
  publish = "./html/prod"

[functions]
  directory = "./functions"

[[redirects]]
  from = "/screenshots/*"
  to = "/.netlify/functions/screenshots/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
