version: 2.1

aliases:
  - &defaults
    docker:
      - image: cimg/node:14.17.0
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  ci:
    <<: *defaults
    steps:
      - checkout
      # - add_ssh_keys # Uncomment to enable --autoRelease
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run:
          name: 'CI Tests'
          command: 'yarn run ci'
          environment:
            ENABLE_VISUAL_REGRESSION_TESTS: 1

workflows:
  version: 2
  # On every commit
  commit:
    jobs:
      - ci
