#!/usr/bin/env bash
set -e

IMAGE_NAME="pixelastic-api-test"
CONTAINER_NAME="yarn-test"

# Build the image
docker build -t $IMAGE_NAME .

# Remove the container if it exists
# 2>/dev/null to remove the output
# || true to prevent the whole script from failing
docker rm $CONTAINER_NAME 2>/dev/null || true

# Create a new container from the image and use it run the tests
docker run \
  --rm \
  --name $CONTAINER_NAME \
  -e "TERM=xterm-256color" \
  --mount type=bind,src=$PWD/mount,dst=/home/circleci/project/hill \
  $IMAGE_NAME \
  ./run
  # yarn run test

# docker run \
#   "$IMAGE_NAME:latest" \
#   "yarn run test"
  
