#!/usr/bin/env bash
set -e

# We need to pass to the Dockerfile the user name and uid, so we can replicate
# the same user in the container
HOST_UID="$(id -u)"
HOST_USER="$USER"

export HOST_UID
export HOST_USER

docker-compose up --build visual
