#!/usr/bin/env bash
set -e

# Disable the opening of the browser
export BROWSER=false

# Kill all background processes started by this script when it ends, or is
# stopped
trap 'kill $(jobs -p)' EXIT

# Start netlify dev
export NETLIFY_SERVER_RUNNING=1
netlify dev &

# Wait for the server to be running
echo -n "Starting netlify dev server"
until curl --output /dev/null --silent --head --fail http://localhost:8888/; do
  echo -n "."
  sleep 1
done

# Running tests (potentially in watch mode)
aberlaas test "$@"
